# Shell variables
# Generated by 'wal'
wallpaper="/home/mav204/dotfiles/wallpaper/CUSTOM/abs1.jpg"

# Special
background='#0e0c1e'
foreground='#c2c2c6'
cursor='#c2c2c6'

# Colors
color0='#0e0c1e'
color1='#32618A'
color2='#5C7490'
color3='#6F8EAA'
color4='#799CC1'
color5='#8F99AE'
color6='#A198A1'
color7='#c2c2c6'
color8='#5e5c70'
color9='#32618A'
color10='#5C7490'
color11='#6F8EAA'
color12='#799CC1'
color13='#8F99AE'
color14='#A198A1'
color15='#c2c2c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
