[colors]
background = '#0e0c1e8e'
black = '#0e0c1e'
blue = '#32618A'
cursor = '#c2c2c6'
cyan = '#5C7490'
foreground = '#c2c2c6'
green = '#6F8EAA'
magenta = '#799CC1'
red = '#8F99AE'
tabs = '#c2c2c6'
tabs-active = '#A198A1'
white = '#c2c2c6'
yellow = '#c2c2c6'
dim-black = '#0e0c1e8e'
dim-blue = '#32618A8e'
dim-cyan = '#5C74908e'
dim-foreground = '#c2c2c68e'
dim-green = '#6F8EAA8e'
dim-magenta = '#799CC18e'
dim-red = '#8F99AE8e'
dim-white = '#A198A18e'
dim-yellow = '#c2c2c68e'
light-black = '#32618A'
light-blue = '#5C7490'
light-cyan = '#6F8EAA'
light-foreground = '#799CC1'
light-green = '#8F99AE'
light-magenta = '#A198A1'
light-red = '#c2c2c6'
light-white = '#32618A'
light-yellow = '#5C7490'
